pyblog-blueprinted/pyblog_project/project/posts/views.py
__author__ = 'mike'

# from flask.ext.sqlalchemy import SQLAlchemy
# from sqlalchemy.exc import IntegrityError
# from forms import AddPost, LoginForm
# from flask.ext.admin import Admin
# from admin import MyView, AuthenticatedMenuLink, MyModel
# from flask.ext.login import LoginManager, logout_user, login_user, current_user, login_required


from flask import Flask, render_template, request, url_for, flash, redirect, session, Blueprint
from project import db
import datetime
from project.models import Post, User



posts_blueprint = Blueprint(
        'posts', __name__,
        url_prefix='/posts',
        template_folder='templates',
        static_folder='static'
    )



# app = Flask(__name__)
# app.config.from_object('config')
# login_manager = LoginManager()
# login_manager.init_app(app)
# db = SQLAlchemy(app)
# admin = Admin(app)
# admin.add_view(MyView(name='Index'))
# login_manager.login_view = 'login'
# from models import Post, User
# admin.add_view(MyModel(Post, db.session))
# admin.add_link(AuthenticatedMenuLink(name='Logout', endpoint='logout'))


@posts_blueprint.route('/')
def home():
    posts = db.session.query(Post).filter_by(status='1').order_by(Post.posted_date.desc())
    return render_template('blog.html', posts=posts)




# @app.route('/add_post', methods=['GET', 'POST'])
# @login_required
# def add_post():
#     form = AddPost(request.form)
#     if request.method == 'POST':
#         post = Post(
#             form.title.data,
#             form.post_body.data,
#             datetime.utcnow(),
#             None,
#             1
#         )
#         db.session.add(post)
#         db.session.commit()
#         return redirect(url_for('home'))
#     return redirect('/admin')


@posts_blueprint.route('/post/<string:post_id>')
def post(post_id):
    new_id = post_id.replace('_', ' ')
    tag = []
    post = db.session.query(Post).filter_by(title=new_id)

    for p in post:
        tag = p.tags.split()
    dt = datetime.date.today()

    return render_template('post.html', post=post, tag=tag, dt=dt)

pyblog-blueprinted/pyblog_project/project/posts/templates/blog.html
{% extends 'template.html' %}

{% block content %}
    {% for post in posts %}
        <div class="posts">
                <h1 class="content-subhead">Post</h1>

                <!-- A single blog post -->
                <section class="post">
                    <header class="post-header">
                        {#<img class="post-avatar" alt="Mike Norman&#x27;s avatar" height="48" width="48" src="img/common/tilo-avatar.png">#}
                        <h2 class="post-title"><a href="{{ url_for('posts.post', post_id=post.title.replace(' ', '_'))}}">{{ post.title }}</a></h2>

                        <p class="post-meta">
                            <i class="fa fa-calendar"></i> <a class="post-category post-date">{{ post.posted_date }}</a>
                        </p>
                    </header>

                    {#<div class="post-description">
                        <p>
                            {{ post.post_body }}
                        </p>
                    </div>#}
                </section>
            </div>
    {% endfor %}

{% endblock %}

pyblog-blueprinted/pyblog_project/project/posts/templates/home.html
{% extends 'template.html' %}

{% block content %}
    {% for post in posts %}
        <div class="posts">
                <h1 class="content-subhead">Post</h1>

                <!-- A single blog post -->
                {#<section class="post">
                    <header class="post-header">
                        <img class="post-avatar" alt="Mike Norman&#x27;s avatar" height="48" width="48" src="img/common/tilo-avatar.png">

                        <h2 class="post-title"><a href="{{ url_for('posts.post', post.task_id) }}">{{ post.title }}</a></h2>

                        <p class="post-meta">
                            By <a href="#" class="post-author">Mike Norman</a> under <a class="post-category post-category-design" href="#">CSS</a> <a class="post-category post-category-pure" href="#">Pure</a>
                        </p>
                    </header>

                   <div class="post-description">
                        <p>
                            {{ post.post_body }}
                        </p>
                   </div>#}
                </section>
            </div>
    {% endfor %}

{% endblock %}

pyblog-blueprinted/pyblog_project/project/posts/templates/post.html
{% extends 'template.html' %}

{% block content %}
    {% for post in post %}
        <div class="posts">

                <h1 class="content-subhead">Date: {{ dt }}</h1>

                <!-- A single blog post -->
                <section class="post">
                    <header class="post-header">
                    {#<img class="post-avatar" alt="Mike Norman&#x27;s avatar" height="48" width="48" src="img/common/tilo-avatar.png">
#}
                        <h2 class="post-title">{{ post.title }}</h2>

                        <p class="post-meta">
                            By <a href="#" class="post-author">{{ post.poster.user_id }}</a>&nbsp;&nbsp; <span class="glyphicon glyphicon-tags"></span> <a class="post-category post-category-{{ post.tags }}">{{ post.tags }}</a>
                        </p>
                    </header>

                    <div class="post-description">
                        <p>
                            {% autoescape false %}
                                {{ post.post_body }}
                            {% endautoescape %}
                        </p>
                    </div>
                </section>
            </div>
    {% endfor %}
    

    </div>

{% endblock %}

{% block disqus%}
      <div id="disqus_thread">
      </div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
       window.onload = function(){ 
       var disqus_shortname = 'entryleveldev'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();}
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    
{% endblock %}